language: java
jdk:
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: Lx+Kvi1DT1n4Nhv3A3IrVu7tENn6bBA1l/ez0u8jrH6maSCB/DmI94wJZB5AMjQZlmAQm/e2J2QiAchEz2kRaLs2kKw/6WLRRI5o+ZXM1Unrqib3PewAaUWRbYL/z5H6t49ZYSd/xkuMEV6kbbIv8mt6VhX6gHHa/3CKSbUX2peoQjDAL3WMHbVMO4tPskC031vTFw5O3KrRi3dqv7Pcyaf+sKyuqEnT5e8HSvlZfn4vSvFqUf75g/grn9+HWF7D2TjujUT/kw1fhfwgoAxL+rTpxlSX3JKJjEUTZX81g0O+pdHXrzwWQO1+2V14y1zI+rgUbfc1O0gZdl+23luIDkWUH5NC1vo3tH8JKhcUkpbrn7P28UzdBjGCcFk+S7Uzf+18Wpl5ZCuLLcMuqyxT7CTtUauXvl3IDNpVZ/RkRgqYdO5psG6+mMsyZMEwpAl/hNMrHtSZFUNd/fpJzgmNbDvixwumpTRzUjKrRVzNkiJXGOU4LFZSk9do1TC3O3cfW51AvJKohQWyWJXxiK8mDrRPLC7AEB/F0OTmudWOMFEmQc6MzcCOU0Na/HbpyAhgmyOUH4aKPXOmDUK5ygZgPxoh+p0ZNlrizIA3KykXTcate68cZoy6xkfWDNaWOV+Ro7mrYUdyj9AJKuvq2V5HAd+PVdihM2TwHFisrq7BGCU=
