language: java
jdk:
- oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: spw7ITLBhMr+ExweijV3WKF9ZdQhFeZe0CSIL/NPsI9bjR01Fn18g/wGkDg4HmFWppNB28TFyYLpccxkMciqVt0jOfuJCe6TDSLSLYzYlTekpjSdtUMcb5n/QPHN/ywtUGWTMiusidRbxRInk2+MgSUZw3n0UrA23aDaYlStiaje1uLXB0b7gFHjjXMPBIi9AvJrrfG7R4A+gjFIAin7tQFVj9evx8aClp34QgBn7uDB7Zwu7Edo9mfQC479NPHNs4wAe96hhuhUG/dbFQYbH74VCGcJA/9kblZNIhN6FHE3Y2KD9CdfoTq6abhyy04OTFHsi+qSsJhqPAG54VkYVOFW7PaOdVPbYEyOqY7hBeSGjyYe1ze/bmJF7JskhGRp3MySWKCUZRljAspz9JAK8NsmgktDMx6t85NdDIBtMerFZBr+sTWjRFePxIMTu1+s4bvqFeE1fuxF9EjVx4U5Bnx9U7c1acWqHYY5R4gj1B8QNNuivajWyMW5po8cCHmCb9jsDlAbMj5zB5IvzcYsiyY/ZViProfvSF7NbXa3I7fZu8pUbVCkzEwbWy0CDNFDPBTWG/nad3Gcovzv6sSfLbTFnicflAWYBOYAM5m/EtVt5BFl9Jp2KWaNLWgNIScjv7QzyFVZhBlfZcMgrVLvAK/4X8jrCep3LjccaSDccGE=
